export const typography = {
  h1: {
    fontFamily: 'System',
    fontSize: 24,
    fontWeight: '500' as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
  h2: {
    fontFamily: 'System',
    fontSize: 20,
    fontWeight: '500' as const,
    lineHeight: 30,
    letterSpacing: 0,
  },
  h3: {
    fontFamily: 'System',
    fontSize: 18,
    fontWeight: '500' as const,
    lineHeight: 27,
    letterSpacing: 0,
  },
  body: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '400' as const,
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodySm: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '400' as const,
    lineHeight: 21,
    letterSpacing: 0,
  },
  bodyXs: {
    fontFamily: 'System',
    fontSize: 12,
    fontWeight: '400' as const,
    lineHeight: 18,
    letterSpacing: 0,
  },
  button: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '500' as const,
    lineHeight: 24,
    letterSpacing: 0,
  },
  title: {
    fontFamily: 'System',
    fontSize: 24,
    fontWeight: '400' as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
  subtitle: {
    fontFamily: 'System',
    fontSize: 16,
    fontWeight: '400' as const,
    lineHeight: 24,
    letterSpacing: 0,
  },
  caption: {
    fontFamily: 'System',
    fontSize: 14,
    fontWeight: '400' as const,
    lineHeight: 20,
    letterSpacing: 0,
  },
  logoEmoji: {
    fontFamily: 'System',
    fontSize: 36,
    fontWeight: '400' as const,
    lineHeight: 36,
    letterSpacing: 0,
  },
};
